### ISSUE TITLE
turbo_demo module doesn't seem to work with connection=local

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/cloud.common#13]
##### SUMMARY

I tried using the turbo_demo module in a playbook that runs on localhost using `connection: local`, but it gives me errors.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

turbo_demo

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.10.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/jgeerling/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.62)]
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/Users/jgeerling/Dropbox/VMs/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

macOS Catalina

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - cloud.common.turbo_demo:
      with_sequence: count=10
```

Run the playbook with `ansible-playbook main.yml`.

##### EXPECTED RESULTS

The demo should succeed.

##### ACTUAL RESULTS

For each of the 10 items in sequence, I get:

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory
failed: [localhost] (item=10) => {"ansible_loop_var": "item", "changed": false, "item": "10", "module_stderr": "Traceback (most recent call last):
  File "/Users/jgeerling/.ansible/tmp/ansible-tmp-1602166944.607778-90470-33953846785094/AnsiballZ_turbo_demo.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/jgeerling/.ansible/tmp/ansible-tmp-1602166944.607778-90470-33953846785094/AnsiballZ_turbo_demo.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jgeerling/.ansible/tmp/ansible-tmp-1602166944.607778-90470-33953846785094/AnsiballZ_turbo_demo.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cloud.common.plugins.modules.turbo_demo', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/modules/turbo_demo.py", line 69, in <module>
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/modules/turbo_demo.py", line 65, in main
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/modules/turbo_demo.py", line 56, in run_module
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 28, in __init__
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 70, in run_on_daemon
  File "/var/folders/mt/rp7cb3s95qzfkrh1dk_8ckfc0000gn/T/ansible_cloud.common.turbo_demo_payload_cikop0vi/ansible_cloud.common.turbo_demo_payload.zip/ansible_collections/cloud/common/plugins/module_utils/turbo/module.py", line 61, in connect
FileNotFoundError: [Errno 2] No such file or directory
", "module_stdout": "", "msg": "MODULE FAILURE
See stdout/stderr for the exact error", "rc": 1}
```

**Comment by goneri** [comment]
It works fine here. Maybe a problem with MacOS instead?

**Comment by goneri** [comment]
I confirm the problem with MacOS.
